from ROOT import TFile
from ROOT import TH1I
from ROOT import TCanvas
from ROOT import TLegend

class ParticleDistributionsFromDelphes(object):

  def __init__(self, fileName):
    self.fileName = fileName
    self.rootFile = TFile(self.fileName)

    self.electronRecoPtDistribution = self.rootFile.Get("electronRecoPtDistribution")
    self.electronLeadingRecoPtDistribution = self.rootFile.Get("electronLeadingRecoPtDistribution")
    self.electronLeadingRecoEtaDistribution = self.rootFile.Get("electronLeadingRecoEtaDistribution")
    self.electronGenPtDistribution = self.rootFile.Get("electronGenPtDistribution")
    self.muonRecoPtDistribution = self.rootFile.Get("muonRecoPtDistribution")
    self.muonLeadingRecoPtDistribution = self.rootFile.Get("muonLeadingRecoPtDistribution")
    self.muonLeadingRecoEtaDistribution = self.rootFile.Get("muonLeadingRecoEtaDistribution")
    self.muonGenPtDistribution = self.rootFile.Get("muonGenPtDistribution")
    self.tauGenPtDistribution = self.rootFile.Get("tauGenPtDistribution")
    self.photonRecoPtDistribution = self.rootFile.Get("photonRecoPtDistribution")
    self.photonLeadingRecoPtDistribution = self.rootFile.Get("photonLeadingRecoPtDistribution")
    self.photonLeadingRecoEtaDistribution = self.rootFile.Get("photonLeadingRecoEtaDistribution")
    self.photonGenPtDistribution = self.rootFile.Get("photonGenPtDistribution")
    self.jetRecoPtDistribution = self.rootFile.Get("jetRecoPtDistribution")
    self.jetLeadingRecoPtDistribution = self.rootFile.Get("jetLeadingRecoPtDistribution")
    self.jetLeadingRecoEtaDistribution = self.rootFile.Get("jetLeadingRecoEtaDistribution")
    self.jetGenPtDistribution = self.rootFile.Get("jetGenPtDistribution")


class HiggsParticleDistributionsPythia(object):

  def __init__(self, fileName):
    self.fileName = fileName
    self.rootFile = TFile(self.fileName)

    self.higgsPtHisto = self.rootFile.Get("higgsPtHisto")
    self.ewBosonPtHisto = self.rootFile.Get("ewBosonPtHisto")
    self.ewBosonLeadingPtHisto = self.rootFile.Get("ewBosonLeadingPtHisto")
    self.ewBosonSubLeadingPtHisto = self.rootFile.Get("ewBosonSubLeadingPtHisto")
    self.chargedLeptonPtHisto = self.rootFile.Get("chargedLeptonPtHisto")
    self.neutralLeptonPtHisto = self.rootFile.Get("neutralLeptonPtHisto")
    self.ewBoson1PtHisto = self.rootFile.Get("ewBoson1PtHisto")
    self.ewBoson2PtHisto = self.rootFile.Get("ewBoson2PtHisto")
    self.lepton1PtHisto = self.rootFile.Get("lepton1PtHisto")
    self.lepton2PtHisto = self.rootFile.Get("lepton2PtHisto")
    self.lepton3PtHisto = self.rootFile.Get("lepton3PtHisto")
    self.lepton4PtHisto = self.rootFile.Get("lepton4PtHisto")
    self.leadingChargedLeptonPtHisto = self.rootFile.Get("leadingChargedLeptonPtHisto")
    self.chargedLeptonLeadingEtaHisto = self.rootFile.Get("chargedLeptonLeadingEtaHisto")
    self.higgsEtaHisto = self.rootFile.Get("higgsEtaHisto")
    self.ewBosonEtaHisto = self.rootFile.Get("ewBosonEtaHisto")
    self.chargedLeptonEtaHisto = self.rootFile.Get("chargedLeptonEtaHisto")
    self.higgsPhiHisto = self.rootFile.Get("higgsPhiHisto")
    self.ewBosonPhiHisto = self.rootFile.Get("ewBosonPhiHisto")
    self.chargedLeptonPhiHisto = self.rootFile.Get("chargedLeptonPhiHisto")

class ResonanceParticleDistributionsPythia(object):

  def __init__(self, fileName):
    self.fileName = fileName
    self.rootFile = TFile(self.fileName)

    self.resonancePtHisto = self.rootFile.Get("resonancePtHisto")
    self.decayPtHisto = self.rootFile.Get("decayPtHisto")
    self.decayLeadingPtHisto = self.rootFile.Get("decayLeadingPtHisto")
    self.decaySubLeadingPtHisto = self.rootFile.Get("decaySubLeadingPtHisto")
    self.decay1PtHisto = self.rootFile.Get("decay1PtHisto")
    self.decay2PtHisto = self.rootFile.Get("decay2PtHisto")
    self.resonanceEtaHisto = self.rootFile.Get("resonanceEtaHisto")
    self.decayEtaHisto = self.rootFile.Get("decayEtaHisto")
    self.decayLeadingEtaHisto = self.rootFile.Get("decayLeadingEtaHisto")
    self.higgsPhiHisto = self.rootFile.Get("higgsPhiHisto")
    self.resonancePhiHisto = self.rootFile.Get("resonancePhiHisto")
    self.decayPhiHisto = self.rootFile.Get("decayPhiHisto")


delphesSim_ff_H_WW_enuenu_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_H_WW_enuenu_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_H_WW_munumunu_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_H_WW_munumunu_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_H_ZZ_eeee_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_H_ZZ_eeee_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_H_ZZ_mumumumu_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_H_ZZ_mumumumu_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_W_enu_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_W_enu_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_W_munu_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_W_munu_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_Z_ee_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_Z_ee_1000events/EWProductionAndHiggs/distributions.root")
delphesSim_ff_Z_mumu_1000events = ParticleDistributionsFromDelphes("DelphesSim_ff_Z_mumu_1000events/EWProductionAndHiggs/distributions.root")

pythia_ff_H_WW_enuenu_1000events = HiggsParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_H_WW_enuenu_1000events/ff_H_WW_enuenu_1000events_plots.root")
pythia_ff_H_WW_munumunu_1000events = HiggsParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_H_WW_munumunu_1000events/ff_H_WW_munumunu_1000events_plots.root")
pythia_ff_H_ZZ_eeee_1000events = HiggsParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_H_ZZ_eeee_1000events/ff_H_ZZ_eeee_1000events_plots.root")
pythia_ff_H_ZZ_mumumumu_1000events = HiggsParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_H_ZZ_mumumumu_1000events/ff_H_ZZ_mumumumu_1000events_plots.root")
pythia_ff_W_enu_1000events = ResonanceParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_W_enu_1000events/ff_W_enu_1000events_plots.root")
pythia_ff_W_munu_1000events = ResonanceParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_W_munu_1000events/ff_W_munu_1000events_plots.root")
pythia_ff_Z_ee_1000events = ResonanceParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_Z_ee_1000events/ff_Z_ee_1000events_plots.root")
pythia_ff_Z_mumu_1000events = ResonanceParticleDistributionsPythia("../pythia8223/pythia-FCC/ff_Z_mumu_1000events/ff_Z_mumu_1000events_plots.root")

# Compare leading lepton distributions in pt and eta

canvas = TCanvas("canvas", "canvas")
canvas.SetGridx()
canvas.SetGridy()
canvas.SetLogy()

# ---- PT COMPARISON ----

# Electrons in H to WW
delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_H_WW_enuenu_1000events.leadingChargedLeptonPtHisto.SetLineColor(2)
leg1 = TLegend(0.7,0.7,0.48,0.9)
leg1.SetHeader("Distributions")
leg1.AddEntry(delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoPtDistribution,"Reco","l")
leg1.AddEntry(pythia_ff_H_WW_enuenu_1000events.leadingChargedLeptonPtHisto,"Gen","l")
delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoPtDistribution.SetTitle("ff_H_WW_enuenu")
delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoPtDistribution.Draw("")
pythia_ff_H_WW_enuenu_1000events.leadingChargedLeptonPtHisto.Draw("SAME")
leg1.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_WW_enuenu_1000events_LeadingElectronPt.svg", "svg")

# Muons in H to WW
delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_H_WW_munumunu_1000events.leadingChargedLeptonPtHisto.SetLineColor(2)
leg2 = TLegend(0.7,0.7,0.48,0.9)
leg2.SetHeader("Distributions")
leg2.AddEntry(delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoPtDistribution,"Reco","l")
leg2.AddEntry(pythia_ff_H_WW_munumunu_1000events.leadingChargedLeptonPtHisto,"Gen","l")
delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoPtDistribution.SetTitle("ff_H_WW_munumunu")
delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoPtDistribution.Draw("")
pythia_ff_H_WW_munumunu_1000events.leadingChargedLeptonPtHisto.Draw("SAME")
leg2.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_WW_munumunu_1000events_LeadingMuonPt.svg", "svg")

# Electrons in H to ZZ
delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_H_ZZ_eeee_1000events.leadingChargedLeptonPtHisto.SetLineColor(2)
leg3 = TLegend(0.7,0.7,0.48,0.9)
leg3.SetHeader("Distributions")
leg3.AddEntry(delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoPtDistribution,"Reco","l")
leg3.AddEntry(pythia_ff_H_ZZ_eeee_1000events.leadingChargedLeptonPtHisto,"Gen","l")
delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoPtDistribution.SetTitle("ff_H_ZZ_eeee")
delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoPtDistribution.Draw("")
pythia_ff_H_ZZ_eeee_1000events.leadingChargedLeptonPtHisto.Draw("SAME")
leg3.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_ZZ_eeee_1000events_LeadingElectronPt.svg", "svg")

# Muons in H to ZZ
delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_H_ZZ_mumumumu_1000events.leadingChargedLeptonPtHisto.SetLineColor(2)
leg4 = TLegend(0.7,0.7,0.48,0.9)
leg4.SetHeader("Distributions")
leg4.AddEntry(delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoPtDistribution,"Reco","l")
leg4.AddEntry(pythia_ff_H_ZZ_mumumumu_1000events.leadingChargedLeptonPtHisto,"Gen","l")
delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoPtDistribution.SetTitle("ff_H_ZZ_mumumumu")
delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoPtDistribution.Draw("")
pythia_ff_H_ZZ_mumumumu_1000events.leadingChargedLeptonPtHisto.Draw("SAME")
leg4.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_ZZ_mumumumu_1000events_LeadingMuonPt.svg", "svg")

# Electrons in W to enu
delphesSim_ff_W_enu_1000events.electronLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_W_enu_1000events.decayLeadingPtHisto.SetLineColor(2)
leg5 = TLegend(0.7,0.7,0.48,0.9)
leg5.SetHeader("Distributions")
leg5.AddEntry(delphesSim_ff_W_enu_1000events.electronLeadingRecoPtDistribution,"Reco","l")
leg5.AddEntry(pythia_ff_W_enu_1000events.decayLeadingPtHisto,"Gen","l")
delphesSim_ff_W_enu_1000events.electronLeadingRecoPtDistribution.SetTitle("ff_W_enu")
delphesSim_ff_W_enu_1000events.electronLeadingRecoPtDistribution.Draw("")
pythia_ff_W_enu_1000events.decayLeadingPtHisto.Draw("SAME")
leg5.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_W_enu_1000events_LeadingElectronPt.svg", "svg")

# Muons in W to munu
delphesSim_ff_W_munu_1000events.muonLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_W_munu_1000events.decayLeadingPtHisto.SetLineColor(2)
leg6 = TLegend(0.7,0.7,0.48,0.9)
leg6.SetHeader("Distributions")
leg6.AddEntry(delphesSim_ff_W_munu_1000events.muonLeadingRecoPtDistribution,"Reco","l")
leg6.AddEntry(pythia_ff_W_munu_1000events.decayLeadingPtHisto,"Gen","l")
delphesSim_ff_W_munu_1000events.muonLeadingRecoPtDistribution.SetTitle("ff_W_munu")
delphesSim_ff_W_munu_1000events.muonLeadingRecoPtDistribution.Draw("")
pythia_ff_W_munu_1000events.decayLeadingPtHisto.Draw("SAME")
leg6.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_W_munu_1000events_LeadingMuonPt.svg", "svg")

# Electrons in Z to ee
delphesSim_ff_Z_ee_1000events.electronLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_Z_ee_1000events.decayLeadingPtHisto.SetLineColor(2)
leg7 = TLegend(0.7,0.7,0.48,0.9)
leg7.SetHeader("Distributions")
leg7.AddEntry(delphesSim_ff_Z_ee_1000events.electronLeadingRecoPtDistribution,"Reco","l")
leg7.AddEntry(pythia_ff_Z_ee_1000events.decayLeadingPtHisto,"Gen","l")
delphesSim_ff_Z_ee_1000events.electronLeadingRecoPtDistribution.SetTitle("ff_Z_ee")
delphesSim_ff_Z_ee_1000events.electronLeadingRecoPtDistribution.Draw("")
pythia_ff_Z_ee_1000events.decayLeadingPtHisto.Draw("SAME")
leg7.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_Z_ee_1000events_LeadingElectronPt.svg", "svg")

# Muons in Z to mumu
delphesSim_ff_Z_mumu_1000events.muonLeadingRecoPtDistribution.SetLineColor(1)
pythia_ff_Z_mumu_1000events.decayLeadingPtHisto.SetLineColor(2)
leg8 = TLegend(0.7,0.7,0.48,0.9)
leg8.SetHeader("Distributions")
leg8.AddEntry(delphesSim_ff_Z_mumu_1000events.muonLeadingRecoPtDistribution,"Reco","l")
leg8.AddEntry(pythia_ff_Z_mumu_1000events.decayLeadingPtHisto,"Gen","l")
delphesSim_ff_Z_mumu_1000events.muonLeadingRecoPtDistribution.SetTitle("ff_Z_mumu")
delphesSim_ff_Z_mumu_1000events.muonLeadingRecoPtDistribution.Draw("")
pythia_ff_Z_mumu_1000events.decayLeadingPtHisto.Draw("SAME")
leg8.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_Z_mumu_1000events_LeadingMuonPt.svg", "svg")

# ---- ETA COMPARISON ----

# Electrons in H to WW
delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_H_WW_enuenu_1000events.chargedLeptonLeadingEtaHisto.SetLineColor(2)
leg9 = TLegend(0.15,0.7,0.3,0.9)
leg9.SetHeader("Distributions")
leg9.AddEntry(delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoEtaDistribution,"Reco","l")
leg9.AddEntry(pythia_ff_H_WW_enuenu_1000events.chargedLeptonLeadingEtaHisto,"Gen","l")
delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoEtaDistribution.SetTitle("ff_H_WW_enuenu")
delphesSim_ff_H_WW_enuenu_1000events.electronLeadingRecoEtaDistribution.Draw("")
pythia_ff_H_WW_enuenu_1000events.chargedLeptonLeadingEtaHisto.Draw("SAME")
leg9.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_WW_enuenu_1000events_LeadingElectronEta.svg", "svg")

# Muons in H to WW
delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_H_WW_munumunu_1000events.chargedLeptonLeadingEtaHisto.SetLineColor(2)
leg10 = TLegend(0.15,0.7,0.3,0.9)
leg10.SetHeader("Distributions")
leg10.AddEntry(delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoEtaDistribution,"Reco","l")
leg10.AddEntry(pythia_ff_H_WW_munumunu_1000events.chargedLeptonLeadingEtaHisto,"Gen","l")
delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoEtaDistribution.SetTitle("ff_H_WW_munumunu")
delphesSim_ff_H_WW_munumunu_1000events.muonLeadingRecoEtaDistribution.Draw("")
pythia_ff_H_WW_munumunu_1000events.chargedLeptonLeadingEtaHisto.Draw("SAME")
leg10.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_WW_munumunu_1000events_LeadingMuonEta.svg", "svg")

# Electrons in H to ZZ
delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_H_ZZ_eeee_1000events.chargedLeptonLeadingEtaHisto.SetLineColor(2)
leg11 = TLegend(0.15,0.7,0.3,0.9)
leg11.SetHeader("Distributions")
leg11.AddEntry(delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoEtaDistribution,"Reco","l")
leg11.AddEntry(pythia_ff_H_ZZ_eeee_1000events.chargedLeptonLeadingEtaHisto,"Gen","l")
delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoEtaDistribution.SetTitle("ff_H_ZZ_eeee")
delphesSim_ff_H_ZZ_eeee_1000events.electronLeadingRecoEtaDistribution.Draw("")
pythia_ff_H_ZZ_eeee_1000events.chargedLeptonLeadingEtaHisto.Draw("SAME")
leg11.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_ZZ_eeee_1000events_LeadingElectronEta.svg", "svg")

# Muons in H to ZZ
delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_H_ZZ_mumumumu_1000events.chargedLeptonLeadingEtaHisto.SetLineColor(2)
leg12 = TLegend(0.15,0.7,0.3,0.9)
leg12.SetHeader("Distributions")
leg12.AddEntry(delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoEtaDistribution,"Reco","l")
leg12.AddEntry(pythia_ff_H_ZZ_mumumumu_1000events.chargedLeptonLeadingEtaHisto,"Gen","l")
delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoEtaDistribution.SetTitle("ff_H_ZZ_mumumumu")
delphesSim_ff_H_ZZ_mumumumu_1000events.muonLeadingRecoEtaDistribution.Draw("")
pythia_ff_H_ZZ_mumumumu_1000events.chargedLeptonLeadingEtaHisto.Draw("SAME")
leg12.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_H_ZZ_mumumumu_1000events_LeadingMuonEta.svg", "svg")

# Electrons in W to enu
delphesSim_ff_W_enu_1000events.electronLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_W_enu_1000events.decayLeadingEtaHisto.SetLineColor(2)
leg13 = TLegend(0.15,0.7,0.3,0.9)
leg13.SetHeader("Distributions")
leg13.AddEntry(delphesSim_ff_W_enu_1000events.electronLeadingRecoEtaDistribution,"Reco","l")
leg13.AddEntry(pythia_ff_W_enu_1000events.decayLeadingEtaHisto,"Gen","l")
delphesSim_ff_W_enu_1000events.electronLeadingRecoEtaDistribution.SetTitle("ff_W_enu")
delphesSim_ff_W_enu_1000events.electronLeadingRecoEtaDistribution.Draw("")
pythia_ff_W_enu_1000events.decayLeadingEtaHisto.Draw("SAME")
leg13.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_W_enu_1000events_LeadingElectronEta.svg", "svg")

# Muons in W to munu
delphesSim_ff_W_munu_1000events.muonLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_W_munu_1000events.decayLeadingEtaHisto.SetLineColor(2)
leg14 = TLegend(0.15,0.7,0.3,0.9)
leg14.SetHeader("Distributions")
leg14.AddEntry(delphesSim_ff_W_munu_1000events.muonLeadingRecoEtaDistribution,"Reco","l")
leg14.AddEntry(pythia_ff_W_munu_1000events.decayLeadingEtaHisto,"Gen","l")
delphesSim_ff_W_munu_1000events.muonLeadingRecoEtaDistribution.SetTitle("ff_W_munu")
delphesSim_ff_W_munu_1000events.muonLeadingRecoEtaDistribution.Draw("")
pythia_ff_W_munu_1000events.decayLeadingEtaHisto.Draw("SAME")
leg14.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_W_munu_1000events_LeadingMuonEta.svg", "svg")

# Electrons in Z to ee
delphesSim_ff_Z_ee_1000events.electronLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_Z_ee_1000events.decayLeadingEtaHisto.SetLineColor(2)
leg15 = TLegend(0.15,0.7,0.3,0.9)
leg15.SetHeader("Distributions")
leg15.AddEntry(delphesSim_ff_Z_ee_1000events.electronLeadingRecoEtaDistribution,"Reco","l")
leg15.AddEntry(pythia_ff_Z_ee_1000events.decayLeadingEtaHisto,"Gen","l")
delphesSim_ff_Z_ee_1000events.electronLeadingRecoEtaDistribution.SetTitle("ff_Z_ee")
delphesSim_ff_Z_ee_1000events.electronLeadingRecoEtaDistribution.Draw("")
pythia_ff_Z_ee_1000events.decayLeadingEtaHisto.Draw("SAME")
leg15.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_Z_ee_1000events_LeadingElectronEta.svg", "svg")

# Muons in Z to mumu
delphesSim_ff_Z_mumu_1000events.muonLeadingRecoEtaDistribution.SetLineColor(1)
pythia_ff_Z_mumu_1000events.decayLeadingEtaHisto.SetLineColor(2)
leg16 = TLegend(0.15,0.7,0.3,0.9)
leg16.SetHeader("Distributions")
leg16.AddEntry(delphesSim_ff_Z_mumu_1000events.muonLeadingRecoEtaDistribution,"Reco","l")
leg16.AddEntry(pythia_ff_Z_mumu_1000events.decayLeadingEtaHisto,"Gen","l")
delphesSim_ff_Z_mumu_1000events.muonLeadingRecoEtaDistribution.SetTitle("ff_Z_mumu")
delphesSim_ff_Z_mumu_1000events.muonLeadingRecoEtaDistribution.Draw("")
pythia_ff_Z_mumu_1000events.decayLeadingEtaHisto.Draw("SAME")
leg16.Draw()
canvas.Update()
canvas.Draw()
canvas.Print("ff_Z_mumu_1000events_LeadingMuonEta.svg", "svg")


raw_input()