Universe = vanilla
job = egammaTriggerRate_leadingJet_CrossMatch_deltaR0.3_DelphesPU140_PU0Curves
cmd = genObjectToL1TObjectConvolutionCurves/runGenJetToL1TJetWorkflowOnCondor.sh
args= -j $(job) -c $(cluster) -i genObjectToL1TObjectConvolutionCurves/egammaRateConfigs/CMSBarrelOnly_PU140DelphesSample_CrossMatch_leadingGenJet_l1tEGamma_deltaR0.3_Transformer.yaml
# Better not to put logs in the same folder, as they are plenty
output = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).out
error = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).err
log = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

requirements=Target.Machine=!="hd-38-02.dice.priv"
request_cpus = 1
request_memory = 5000
request_disk = 1000000

queue 5
