Universe = vanilla
job = jetTriggerRate_100TeV_leadingJet_CrossMatch_deltaR0.3_511MEvents
cmd = mySubmitStuff/runTriggerWorkflowOnCondor.sh
args= -j $(job) -c $(cluster) -p $(process) -i genObjectToL1TObjectConvolutionCurves/jetRateConfigs/finalConfigs/FCC_CrossMatch_25GeVPtCut_leadingGenJet_l1tJet_511MEvents_deltaR0.3_100TeV_CMSTunedSample_batchSubmission.yaml
# Better not to put logs in the same folder, as they are plenty
output = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).out
error = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).err
log = /storage/sb17498/logs/heppy/$(job)_$(cluster).$(process).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

requirements=Target.Machine=!="hd-38-02.dice.priv"
request_cpus = 1
request_memory = 5000
request_disk = 1000000

queue 200
